"use strict";
exports.__esModule = true;
var libreria_1 = require("./libreria");
var libro_1 = require("./libro");
var revista_1 = require("./revista");
var cliente_1 = require("./cliente");
var genero1 = "fantasia";
var listagenero = [genero1];
var autor1 = "George Martin";
var autor2 = "Stan Lee";
var autor3 = "Steve Ditko";
var listaAutores = [autor1, autor2, autor3];
var libro1 = new libro_1.Libro("Fire and Blood", autor1, 8900, 1560, "", genero1);
var libro2 = new libro_1.Libro("Dance of Dragons", autor1, 5600, 590, "", genero1);
var listaLibros = [libro1, libro2];
var revista1 = new revista_1.Revista("The Amazing Spiderman", autor3, 1300, 56, 1989);
var revista2 = new revista_1.Revista("The Avengers", autor2, 1000, 34, 1994);
var revista3 = new revista_1.Revista("The X-Men", autor3, 1800, 54, 2001);
var listaRevista = [revista1, revista2, revista3];
var compra1 = [revista1];
var compra2 = [libro2, revista3, libro1];
var compra3 = [listaLibros];
var listaDeCompras = [compra1, compra2, compra3];
var cliente1 = new cliente_1.Cliente("Matias", "Moraschetti", 34545455, "Ushuaia 456", [autor1], [genero1], 0.1);
var cliente2 = new cliente_1.Cliente("xxxx", "xxxx", 11111, "xxxxx", listaAutores, listagenero, 0.3);
var listaClientes = [cliente1, cliente2];
var libreria1 = new libreria_1.Libreria(listaClientes, listaLibros, listaRevista);
console.log(cliente1);
console.log(cliente2);
libreria1.aplicarDescuento(cliente1, libro1);
console.log(libreria1);
